### ISSUE TITLE
build_kernel.sh has some errors

### ISSUE THREAD

**Issue by maedot-d** [Tkkg1994/SM-G930F#1]
Hi, 
Many thanks for your work, effort, and for making such a nice and easy to follow script.
I was trying to build a custom kernel and wanted to test if I can build your variant successfully. I tried the build_kernel.sh script and had some errors. Shouldn't the following be corrected?
-line 75: the directory for the dtbTool be in the scripts/ rather than tools/
-line 88 be: cd "$BUILD_KERNEL_OUT_DIR/arch/$ARCH/boot/dts", and
-line 97: dtb path option should be -d (rather than -p)
With these changes I was able to build the kernel. But now I have one question. How do I create a flashable kernel image?
Thanks for your help in advance.
maedot

**Comment by Tkkg1994** [comment]
Hello maedot-d

I actually don't use this build script for building my kernel at all, but it surely helps others (like you) to know what you should do.
Coming to the flash-able zip, you need to have a look into a stock boot.img file and unpack it, than replace zImage and dtb image with your generated one, than repack boot.img.
After that you can have a look at my zip file how I flash the kernel, should work fine for you as well

**Comment by oxff** [comment]
Can you share how you build your kernel?

I've tried to build the stock sources released by Samsung for G930F just using the defconfig and then make (and then modifying existing boot.img using abootimg). And that does not really work.

**Comment by Tkkg1994** [comment]
well, I just use make -j LOL

**Comment by maedot-d** [comment]
Hi Tkkg1994,
Thanks for the feedback, I appreciate it very much. I understand that you have put a lot of effort in putting this resource together and took the biggest step in sharing it with the public. 

Actually that is exactly what I have been doing for the last two days using different tools (mkbootimg_tool, bootimg-tools, ...). But My custom kernel could not boot. Then I tried the simplest thing: to unpack and repack the original stock img as it is without any modification and I noticed that, even then some KB of data is lost in the process (orig 37MB  but new 36.4MB) and I could not figure out till now as what this information could be.

**Comment by oxff** [comment]
Likewise, been using normal Makefile on SM-G925F without problems and it did not work on SM-G930F, even using exactly the same toolchain that Samsung used on their production kernels.

What are you using for repackaging? I've just used `abootimg -u boot.img -k $kernel/arch/arm64/boot/Image` on a stock boot.img that otherwise runs fine when flashed.

**Comment by kykdev** [comment]
@oxff You mean google's aarch64-linux-android-4.9? That made me suffer from bootloops for months, try another toolchain like sm, uber or linaro. I use arter97's linaro toolchain. https://github.com/arter97/linaro-64/tree/6.1

**Comment by maedot-d** [comment]
@oxff  abootimg leaves out the dt.img, for nexus devices it is not a problem because kernel make creates a zImage-dtb file, but for samsung it somehow doesn't even extract it (it gives just a zImage, which I assume has the dtb inside but ....). That was my fist challenge to figure this out. Then I used other boot.img makers (they come with instructions to unpack and repack) with no avail till now.

**Comment by Tkkg1994** [comment]
I use this toolchain here: http://sabermod.com/Toolchains%20%28DEV%20ONLY%29/aarch64/aarch64-kernel/GCC%205.3/

I also had a none booting kernel with UBERT toolchain

**Comment by oxff** [comment]
What confuses me is that the stock Samsung kernel was built with "gcc version 4.9.x-google 20140827 (prerelease) (GCC)" and that is exactly the toolchain I am using myself.

@Tkkg1994, what tool did you use to place the new kernel into boot.img, respectively for DTB?

@maedot-d, any idea why SM-G925F worked with abootimg? Does it not need the DTB?


Thanks guys for your help!

**Comment by maedot-d** [comment]
@Tkkg1994 that is also the same toolchain I used, as per your listed steps in XDA-dev post.
@oxff no idea, haven't tired G925F yet.

**Comment by oxff** [comment]
@maedot-d Can you share a link to that XDA post? I feel like I'm missing a trivial step. What I've tried right now (all on stock Samsung release tarball):

- "gcc version 4.9.x-google 20140827 (prerelease) (GCC)" 
- SaberMod 4.9.x Tool Chain (latest)

- abootimg (no DTB support but I just replaced zImage)
- xiaolu's mkbootimg_tools (latest, just kept stock dt.img)

All of those gave me a kernel that gets the device very hot but does not actually boot (likely an early hang / infinite loop?).

**Comment by Tkkg1994** [comment]
@maedot-d and @oxff 
here you go (only for you two ;) ): https://github.com/Tkkg1994/SM-G930F/commit/d35483193dcc70e7985499ae79ade41904c5a8ef

**Comment by oxff** [comment]
Awesome, thanks! Can you share what repackaging tool works for you?

**Comment by Tkkg1994** [comment]
Did you ever look in ramdisk? https://github.com/Tkkg1994/SM-G930F/tree/master/ramdisk/SM-G930F

**Comment by maedot-d** [comment]
@Tkkg1994 Many many thanks, the ramdisk folder was the key, I overlooked!!

**Comment by abazad** [comment]
@Tkkg1994 
bro, which version do you use ubuntu? i use 16.04.
 i totally use stock your kernel repo, i compiled kernel your new build.sh, i flashed boot.img and i have error "kernel is not sea enforcing bla bla and bootloop.

**Comment by maedot-d** [comment]
Solved issue.
